require "json"

# Returns the newest simulator on the latest installed iOS runtime whose name matches `pattern`
def newest_simulator(pattern)
  runtimes = JSON.parse(`xcrun simctl list devices available -j`)["devices"]
  latest_ios = runtimes.keys.grep(/SimRuntime\.iOS-/).max_by { |k| k[/iOS-([\d-]+)/, 1].split("-").map(&:to_i) }
  runtimes[latest_ios]
    .map { |d| d["name"] }
    .grep(pattern)
    .max_by { |name| name.scan(/\d+/).map(&:to_i) }
end

app_identifier "com.mycompany.ImperialWeather"
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
# Matches the App Store's required 6.9" iPhone and 13" iPad sizes, using the newest installed model of each
devices([
   newest_simulator(/^iPhone \d+ Pro Max$/),
   newest_simulator(/^iPad Pro 13-inch \(M\d+\)$/)
])

languages([
   "en-US",
   "es-ES"
])

# The name of the scheme which contains the UI Tests
scheme "ImperialWeatherUITests"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots true

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
